# These are supported funding model platforms

github:[aidlearning] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: http://www.aidlearning.net# Replace with a single custom sponsorship URL
